---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-businesslogic-main
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/businesslogic/digitalwarehouse.key" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/businesslogic/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}