---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-main
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/identitymanagement/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-templates
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/identitymanagement/templates/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-copy
  namespace: {{ .Values.nSpace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-idms" | quote }}