---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-main
  namespace: {{ .Values.namespace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/notificationmanager/binary/SourceSansPro-Regular.ttf" "configs/notificationmanager/binary/SourceSansPro-Regular.ttf.customer" "configs/notificationmanager/binary/taraji.jpeg" "configs/notificationmanager/binary/tt.jpeg" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/notificationmanager/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}